### ISSUE TITLE
Use transparent logo

### ISSUE THREAD

**Issue by seagyn** [seagyn/south-africa-covid-19-banner#2]
The logo currently has a white background which means people can't use a background of their choosing. Need to source and replace the logo with one that doesn't have a background.

**Comment by hlashbrooke** [comment]
I ran the image through removebg.com and came out with this:

![sacv-transparent](https://user-images.githubusercontent.com/1543143/78002803-01931280-7338-11ea-9475-e6d7abf4d846.png)

There are some minor white artefacts showing still, but feel free to use it if you're happy with it.

**Comment by seagyn** [comment]
Seems to work. Not amazing but it's better than nothing.
